[package]
name = "bevy_malek_async"
version = "0.3.0"
edition = "2024"
readme = "README.md"
authors = ["pocmalek@gmail.com"]
license = "MIT OR Apache-2.0"
description = "async runtime agnostic access to the bevy ecs"
keywords = ["bevy", "async"]

[features]
default = ["std", "bevy_tasks"]

std = [
    "bevy_app/std",
    "bevy_ecs/std",
    "bevy_platform/std",
    "scoped_static_storage/std",
    "keyed_concurrent_queue/std",
]

[dependencies]
# bevy
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_ecs_macros.workspace = true
bevy_platform.workspace = true
bevy_tasks = { workspace = true, optional = true }

# other
scoped_static_storage.workspace = true
keyed_concurrent_queue.workspace = true
thiserror.workspace = true
crossbeam.workspace = true
async-channel.workspace = true
futures.workspace = true

[package.metadata.docs.rs]
rustdoc-args = [
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--generate-macro-expansion",
]
all-features = true

[workspace]
members = [
    ".",
    "examples/async_bridge_primitive",
    "examples/tokio_example",
]

[workspace.dependencies]
# library crates
bevy_malek_async = { path = "." }

# bevy (temporarily pinned at pre-feathers commit)
bevy_app = { version = "0.18.1", default-features = false }
bevy_ecs = { version = "0.18.1", default-features = false }
bevy_ecs_macros = { version = "0.18.1" }
bevy_platform = { version = "0.18.1", default-features = false }
bevy_tasks = { version = "0.18.1", default-features = false }

# dependencies
scoped_static_storage = { version = "0.1.2", default-features = false }
keyed_concurrent_queue = { version = "0.1.3", default-features = false }
thiserror = { version = "2", default-features = false }
crossbeam = "0.8.4"
async-channel = "2.5.0"
futures = "0.3.32"

# example dependencies
rand = "0.10.1"
futures-timer = "3.0.3"
tokio = { version = "1.52.1", features = ["full"] }
reqwest = "0.13.2"
